# Generated by Django 4.1.7 on 2023-02-15 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='image',
        ),
    ]
